= {lab_name}
include::_attributes.adoc[]

== Lab Overview

This lab will illustrate how the use of various AI/ML technologies can be combined to produce a valuable solution to a business problem.

The information, code, models and techniques it contains are illustrations of what a first prototype could look like. It is not the definitive way of addressing the stated requirements.

== Timetable

This is a tentative timetable for the materials that will be presented today.

[width="90%",cols="3,^2,^2,10",options="header"]
|=========================================================
| Name |Duration |Type |Description

|Background |5 | Presentation
a|- We describe what the desired end state looks like.
- Describe overall user experience and underlying architecture.
- Share mockups for better visualization

|Connection and Setup |10 | Hands-On
a|- Attendees get connected
- help validate environment health
- setup the playpen project

|LLM |20 | Hands-On
a|- summarization check
- sentiment check
- Model Comparison check and choice
- prompt engineering exercise
- sanity-check pipeline

|Image Processing |20 | Hands-On
a|- car recognition checks
- re-training exercise
- model deployment (automated)

|Web App  |20 | Hands-On
a|- deployment
- update

|Productization  |15 | Presentation + discussion
a|- What else could we add that would have value?
- What else could we do following the same patterns?

|=========================================================


== Contributing

If you are interested in contributing to this project, consult this GitHub Repo: https://github.com/rh-aiservices-bu/insurance-claim-processing/[https://github.com/rh-aiservices-bu/insurance-claim-processing/,window=_blank]