FROM registry.access.redhat.com/ubi9/nodejs-18 as stage

USER root

WORKDIR /tmp

RUN git clone https://github.com/rh-aiservices-bu/insurance-claim-processing.git

FROM registry.access.redhat.com/ubi9/nodejs-18

USER root

COPY --from=stage /tmp/insurance-claim-processing/app/ /tmp/src

RUN chown -R 1001:0 /tmp/src

USER 1001

RUN /usr/libexec/s2i/assemble

CMD /usr/libexec/s2i/run
