---
kind: Secret
apiVersion: v1
metadata:
  name: secret-minio
  labels:
    app: ic-app-minio
  annotations:
    argocd.argoproj.io/sync-wave: "0"
stringData:
  aws_access_key_id: minio
  aws_secret_access_key: minio123
type: Opaque